[Repositories]

[[Sample_Repo_1]]
name = "haha1"
url = "gitman.git"
branch = "master"
build_command = "mvn clean install"

[[Sample_Repo_1]]
name = "haha2"
url = "gitman.git"
branch = "master"
build_command = "mvn clean install"

[[Sample_Repo_2]]
name = "lmao1"
url = "gitman.git"
branch = "master"
build_command = "mvn clean install"

[[Sample_Repo_2]]
name = "lmao2"
url = "gitman.git"
branch = "master"
build_command = "mvn clean install"